spring.config.import=optional:file:.env[.properties]

spring.application.name=url-shortener

server.port=8086

## App Config
app.base-url=http://localhost:8086
app.default-expiry-in-days=30
app.validate-original-url=true

# Database Connection
spring.datasource.url=${LOCAL_DB_URL}
spring.datasource.username=${LOCAL_DB_USERNAME}
spring.datasource.password=${LOCAL_DB_PASSWORD}

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

#spring.sql.init.mode=embedded (for embedded database H2)
#spring.sql.init.mode=always

## Spring Security
#spring.security.user.name=kishore
#spring.security.user.password=kvnf
#spring.security.user.roles=USER,ADMIN
